命令稿啟動於 2018年03月14日 下午 10:23:37
]0;~
[32muser@DESKTOP-83NB8QN [33m~[0m
$ whoami; pwd
user
/home/user
]0;~
[32muser@DESKTOP-83NB8QN [33m~[0m
$ git config -l
user.email=erichuang1203@gmail.com
user.name=borsheng
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
]0;~
[32muser@DESKTOP-83NB8QN [33m~[0m
$ git clone https://github.com/borsheng/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;~
[32muser@DESKTOP-83NB8QN [33m~[0m
$ D[Kexit

命令稿已於 2018年03月14日 下午 10:24:50
 完成